### ISSUE TITLE
suggest(char-counter): a minimum limit for the popup to show

### ISSUE THREAD

**Issue by RGBCube** [Gabe616/VendettaPlugins#11]
### Check all the boxes below

- [X] I have checked that this feature hasn't already been suggested

### Discord username

@rgbcube

### Simple description

A setting that defaults to 0 which makes the char count popup only show if the number is determined by the user is passed.

### Elaborate

Nothing more to elaborate

**Comment by Gabe616** [comment]
will work on this in the near future (a few days probably)

**Comment by RGBCube** [comment]
thanks 👍
