### ISSUE TITLE
bug(char-counter): plugin crash

### ISSUE THREAD

**Issue by Rairof** [Gabe616/VendettaPlugins#12]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@rairof

### Detailed Info

Vendetta crash

### Steps to Reproduce

1. Get vendetta
2. Install ChatCounter plugin

### Crash Info

N/A

### Bug Screenshot

![Screenshot_2023-07-12-14-51-15-217_dev beefers vendetta-edit](https://github.com/Gabe616/VendettaPlugins/assets/107706560/33a5ec5b-5376-4c24-b814-e5452ade74af)

### System Info

Device: Xiaomi 11T pro
Manufacturer: Xiaomi
Brand: Xiaomi

OS: MIUI
Version: 14.0.3

Discord Branch: beta
Discord Version: 187.9
Discord Build: 187.9
Vendetta Version: 5c37b91

React Version: 18.2.0
Hermes Bytecode: 89
![Screenshot_2023-07-12-14-51-26-474_dev beefers vendetta-edit](https://github.com/Gabe616/VendettaPlugins/assets/107706560/37a498c8-c0da-4e4a-93f9-b559785b43fb)

**Comment by Gabe616** [comment]
should be fixed in newest (unproxied) version
