### ISSUE TITLE
bug(nexxutils/listen along): "listen along" in my profile

### ISSUE THREAD

**Issue by riichimaru** [Gabe616/VendettaPlugins#14]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@riichimaru

### Detailed Info

"listen along" button is also for your own profile. if you press it, it will clear your queue and leave only the playing song.

i think it should be removed in *your own* profile

### Steps to Reproduce

1. go to your own profile with music on
2. press on "listen along" button
3. look at spotify queue

### System Info

[**Device**]
> Device: realme RMX2061
> Model: RMX2061
> Manufacturer: realme
> Brand: realme
> Display: 1080x2400

[**Hardware**]
> CPU Cores: 8
> Network: Cellular 4G

[**Software**]
> OS: Android
> Version: 13
> SDK Version: 33

[**Discord**]
> Branch: googleRelease
> Version: 186.11
> Build: 186011
> Vendetta: cf09dbc
> CPU Usage: 20.31%
> Memory Usage: 598 MB

[**React**]
> Version: 18.2.0
> Hermes Bytecode: 89
> Hermes: for RN 0.70.6
> Native: 0.70.6

**Comment by Gabe616** [comment]
oops will fix this

**Comment by riichimaru** [comment]
also found out that spotify has to play sth before pressing the actual "listen along" button

**Comment by Gabe616** [comment]
completely overhauled listen along + fixed those two bugs:
- listen along on your own profile
- not syncing when not playing anything
![image](https://github.com/Gabe616/VendettaPlugins/assets/60316309/90926656-ba6f-4c33-b574-5286f51a73c1)
