### ISSUE TITLE
suggest(MonetTheme): Make themes exportable.

### ISSUE THREAD

**Issue by rickdtc** [Gabe616/VendettaPlugins#15]
### Check all the boxes below

- [X] I have checked that this feature hasn't already been suggested

### Discord username

@knockdemput 

### Simple description

An option to export the generated themes as json to use like normal themes, or to make a better theme basing off it.

### Elaborate

A button to export theme to device storage as a vendetta theme json.

**Comment by Gabe616** [comment]
gonna have to decline this
