### ISSUE TITLE
bug(cloud-sync): non-downloadable addons break importing

### ISSUE THREAD

**Issue by Panniku** [Gabe616/VendettaPlugins#25]
### Check all the boxes below

- [X] I have checked that this bug hasn't already been reported

### Discord username

@panniku

### Detailed Info

when attempting to load data, some themes fail to fetch
this is due to a few themes being unablw to be fetched resulting in all the other themes after it failing to be synced 

### Steps to Reproduce

1. Go to Settings
2. Have one theme which cannot be refetched (optional: above a few themes)
3. Save Data in the CloudSync plugin
4. After saving data, wait a few seconds and Load data

Expected:
- All data loads

Result:
- The broken theme and the other themes below it fail to be fetched

### System Info

__System Information__

[**Device**]
> Device: samsung SM-A525F
> Model: SM-A525F
> Manufacturer: samsung
> Brand: samsung
> Display: 1080x2400
[**Hardware**]
> CPU Cores: 8
> Network: WiFi
[**Software**]
> OS: Android
> Version: 13
> SDK Version: 33
[**Discord**]
> Branch: canaryRelease
> Version: 191.8
> Build: 191208
> Vendetta: ee76885
> CPU Usage: 12.97%
> Memory Usage: 622 MB
[**React**]
> Version: 18.2.0
> Hermes Bytecode: 94
> Hermes: for RN 0.72.3-discord-6
> Native: 0.72.3-discord-6

**Comment by Gabe616** [comment]
fixing rn, will update cloud sync in a few minutes

**Comment by Gabe616** [comment]
fixed!!
