### ISSUE TITLE
suggest(use-system-emoji): apply everywhere

### ISSUE THREAD

**Issue by Quinxxxx** [Gabe616/VendettaPlugins#8]
### Check all the boxes below

- [x] I have checked that this feature hasn't already been suggested

### Discord username

@moodalicious

### Simple description

system emoji applied to more places

### Elaborate

be able to make system emojis replace twemoji in the discord emoji keyboard + reactions and so when we tap on them it shows the emoji

**Comment by Quinxxxx** [comment]
thank you sir

**Comment by Gabe616** [comment]
not sure if this is possible since emojis are rendered native side, will continue searching tho

**Comment by Gabe616** [comment]
sadly this is impossible, sorry

**Comment by Quinxxxx** [comment]
> sadly this is impossible, sorry

Alright; thanks for trying though, much appreciated
